name: Notion2Github
on:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # daily
  workflow_dispatch:
jobs:
  auto-sync-from-notion-to-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: notion-blog
        uses: xzebra/notion-blog@master
        with:
          database-id: 'https://www.notion.so/xzebra/f887dfac795547ff97a81bb669b1052f'
          content-folder: web/content
          images-folder: web/static/images/posts
          images-source: /images/posts
          filter-prop: 'Status'
          filter-value: 'Finished ✅'
        env:
          NOTION_SECRET : ${{ secrets.NOTION_SECRET }}

      - name: Format documents
        uses: creyD/prettier_action@v3.1
        with:
          prettier_options: --write ./web/content/**/*.md
          commit_message: 'docs: Update docs (auto)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
